fullnameOverride: qa1-langfuse

langfuse:
  databaseUrl: "postgresql://langfuse_user:your_postgres_password@qa1-langfuse-postgresql.qa1.svc.cluster.local:5432/langfuse"
  redis:
    host: qa1-langfuse-redis.qa1.svc.cluster.local
    port: 6379
  salt:
    secretKeyRef:
      name: langfuse-secrets
      key: salt
  nextauth:
    secret:
      secretKeyRef:
        name: langfuse-secrets
        key: nextauth_secret
  clickhouse:
    enabled: true
    auth:
      username: default
      password: your_clickhouse_password
    host: qa1-langfuse-clickhouse.qa1.svc.cluster.local
    port: 9000
    zookeeper:
      nodes:
        - host: qa1-langfuse-zookeeper.qa1.svc.cluster.local
          port: 2181
  clickhouseUrl: "http://qa1-langfuse-clickhouse.qa1.svc.cluster.local:8123"  # ← added

postgresql:
  enabled: true
  fullnameOverride: qa1-langfuse-postgresql
  auth:
    username: langfuse_user
    password: your_postgres_password
    database: langfuse


redis:
  enabled: true
  fullnameOverride: qa1-langfuse-redis
  auth:
    password: your_redis_password


zookeeper:
  enabled: false
  fullnameOverride: qa1-langfuse-zookeeper

s3:
  enabled: true
  fullnameOverride: qa1-langfuse-s3
  auth:
    rootUser: minio
    rootPassword: miniosecret
