apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qa1-langfuse.fullname" . }}-config
  labels:
    app: {{ include "qa1-langfuse.name" . }}
data:
  LANGFUSE_ENV: "production"
  LANGFUSE_REGION: "us-east-1"
