apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qa1-langfuse.fullname" . }}-secrets
  labels:
    app: {{ include "qa1-langfuse.name" . }}
type: Opaque
stringData:
  salt: "mysalt"
  nextauth_secret: "mysecret"
