apiVersion: v1
kind: Service
metadata:
  name: {{ include "qa1-langfuse.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "qa1-langfuse.name" . }}
    helm.sh/chart: {{ include "qa1-langfuse.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
